name: Compile Sketch

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board: |
          - fqbn: "ATTinyCore:avr:attinyx5micr"
          - fqbn: "esp32:esp32:adafruit_qtpy_esp32s2"
          - fqbn: "esp32:esp32:XIAO_ESP32C3"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile 
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - name: "ATTinyCore:avr"
              source-url: "https://github.com/SpenceKonde/ATTinyCore/archive/1.5.2.zip"
              source-path: "./avr/"
            - name: "arduino:avr"
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - ./
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - name: "Adafruit NeoPixel"
